# Generated by Django 4.2.7 on 2023-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=150)),
                ('vdc', models.CharField(blank=True, max_length=100, null=True)),
                ('vdc_date', models.CharField(blank=True, max_length=12, null=True)),
                ('iro_address', models.CharField(max_length=50)),
                ('iro_date', models.CharField(max_length=12)),
                ('smi_address', models.CharField(max_length=50)),
                ('smi_date', models.CharField(max_length=12)),
                ('capital', models.CharField(max_length=20)),
                ('capital_new', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('pro_name', models.CharField(max_length=100)),
                ('firm_type', models.CharField(choices=[('Sole Prorprietorship', 'Sole Proprietorship'), ('Private Limited', 'Private Limited'), ('Corporation', 'Corporation'), ('Partnership', 'Partnership'), ('Limited Liability Company', 'Limited Liability Company')], max_length=100)),
                ('exp_year', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('pre_sales', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('pre_networth', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('cur_sales', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('cur_networth', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('business_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product_types', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('brand_types', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
