# Generated by Django 4.2.7 on 2023-11-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=30)),
                ('plot_owner', models.CharField(max_length=100)),
                ('plot_add', models.CharField(max_length=150)),
                ('valuator', models.CharField(max_length=100)),
                ('distress_amt', models.FloatField(max_length=50)),
                ('margin', models.FloatField(max_length=50)),
                ('mortgaged_amt', models.CharField(blank=True, max_length=50, null=True)),
                ('building_value', models.CharField(blank=True, max_length=5, null=True)),
                ('building_storey', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
